train:
  batch_size: 65536
  gpus: 0  #0:cpu, 1:gpu
  lr: 0.0002
  weight_decay: 0.00
  opt_eps: 1e-9
  beta1: 0.9
  beta2: 0.999

data:
  image: './figure/figure2e_nuwave.png' #[500, 400, 4(rgba)]

arch:
  layers: 8 
  channels: 64
  init_scale: 30.

log:
  name: 'coin'
  checkpoint_dir: '/checkpoint'
  tensorboard_dir: '/tensorboard'  # default는 tensorboard
