# # hyper_hparameter.yaml

# train:
#   batch_size: 32
#   gpus: 0  # GPU를 사용하지 않으면 0으로 설정
#   max_epochs: 1000  # 최대 epoch 수
# optimizer:  
#   name: "adam"
#   lr: 1e-4  # 학습률
#   weight_decay: 1e-5
# scheduler:
#   name: "step"
#   step_size: 10000
#   gamma: 0.5


# model:
#   # input_dim: 2        # 입력 좌표(x, y) 차원
#   # output_dim: 3       # 출력 RGB 차원
#   # hidden_dim: 256     # 모델의 히든 레이어 차원 수
#   in_features: 64
#   out_features: 5
#   hidden_features: 256
#   hidden_layers: 3 
#   channels: 64
#   init_scale: 30
#   num_layers: 8       # 모델의 레이어 수
#   activation: "sine"  # 활성화 함수 (SIREN 모델이므로 sine 함수 사용)

# data:
#   image_dir: "C:/Users/신유진/workspaces/vscodeprojects/mindslab_ai_test/coin_coding_test/figure/"  # 이미지 파일들이 저장된 디렉토리
#   image_format: ".png"  # 파일 형식 (여기선 .png)

# loss:
#   name: "mse"  # 손실 함수로 Mean Squared Error 사용

# checkpoint:
#   save_top_k: 3        # 최상위 3개의 체크포인트 저장
#   monitor: "val_loss"  # 검증 손실값 기준으로 체크포인트 저장
#   mode: "min"          # 손실값이 최소일 때 체크포인트 저장

# log:
#   name: "coin_multitarget"
#   tensorboard_dir: "/tensorboard/hyper"       # 로그 저장 디렉토리
#   checkpoint_dir: "/checkpoint/hyper"  # 체크포인트 저장 디렉토리


train:
  batch_size: 65536
  gpus: 0  # 0:cpu, 1:gpu
  lr: 0.0002
  weight_decay: 0.00
  opt_eps: 1e-9
  beta1: 0.9
  beta2: 0.999

data:
  images:  # Paths to all five images
    - './figure/figure2a_orig.png'
    - './figure/figure2b_linear.png'
    - './figure/figure2c_someother.png'
    - './figure/figure2d_moreimages.png'
    - './figure/figure2e_nuwave.png'

arch:
  layers: 8 
  channels: 64
  init_scale: 30.

log:
  name: 'hyper_coin'
  checkpoint_dir: '/checkpoint/hyper'
  tensorboard_dir: '/tensorboard/hyper'
